mysite/draw/urls.py
from django.conf.urls import url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    url(r'^home/$', views.home, name='home'),
    url(r'^charts/$', views.charts, name='charts'),
    url(r'^file/download.gml$', views.download, name='download'),
    url(r'^data.csv$', views.dataTsv, name='dataTsv'),
    url(r'^fileupload/$', views.fileupload, name='fileupload'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^draw/', include('draw.urls')),
    url(r'^admin/', admin.site.urls),
]

mysite/draw/forms.py
# coding:utf-8
from django import forms
# LAYOUT_CHOICES = (
#     ('spring', 'spring'),
#     ('random', 'random'),
#     ('spectral', 'spectral'),
#     ('shell', 'shell'),
#     ('circular', 'circular'),
# )
# CLUSTERING_METHOD_CHOICES = (
#     ('modularity', 'modularity'),
#     ('ip_seg', 'ip_seg'),
# )
# IP_SEG_CHOICES = (
#     ('1','1'),
#     ('2','2'),
#     ('3','3'),
#     ('4','4'),
# )

class UploadFileForm(forms.Form):
    upload_file = forms.FileField(label="upload_file",
                                  widget=forms.FileInput(attrs={'class': 'test_form', 'text':'please'}))

# class SettingsForm(forms.Form):
#     clustering_method = forms.ChoiceField(label='clustering_method',
#                                           required=True,
#                                           choices=CLUSTERING_METHOD_CHOICES,
#                                           widget=forms.RadioSelect(attrs={'class': 'clustering_method'}))
#     choose_ip_seg = forms.ChoiceField(label='choose_ip_seg',
#                                       choices=IP_SEG_CHOICES,
#                                       widget=forms.RadioSelect(attrs={'class': 'choose_ip_seg'}))
#     with_node_style = forms.BooleanField(label="with_node_style",
#                                     widget=forms.NullBooleanSelect(attrs={'class': 'with_node_style'}))
    # layout = forms.ChoiceField(label="layout",
    #                            choices=LAYOUT_CHOICES,
    #                            widget=forms.RadioSelect(attrs={'class': 'layout'}))
    # colorful = forms.BooleanField(label="colorful",
    #                               widget=forms.NullBooleanSelect(attrs={'class': 'colorful'}))
    # with_weight = forms.BooleanField(label="with_weight",
    #                                  widget=forms.CheckboxInput(attrs={'class': 'with_weight'}))

mysite/draw/views.py
# coding: utf-8
from django.shortcuts import render, redirect, reverse, render_to_response
import sys
from django.conf import settings
from django.http import HttpResponse
import os, json
from .forms import UploadFileForm
from .models import UploadFile
from algo import graph_utils as gu
from algo.interface import *

def home(request):
    print "script: views.py,  lineNumber:", sys._getframe().f_lineno,  ",  requst.method: ", request.method
    global graph_loaded
    graph_loaded = "false"
    request.session.set_expiry(0)

    if request.method == "GET":
        print "script: views.py,  lineNumber: ", sys._getframe().f_lineno, ",  request.GET: ", request.GET
        if "check_ip" in request.GET.keys():
            ip = request.GET['check_ip']
            db_file_path = os.path.join(settings.BASE_DIR, 'graph.db')
            info = checkIpInfo(ip, db_file_path)
            return HttpResponse(json.dumps(info), content_type="application/json")
        upload_file_form = UploadFileForm()
        context = {
            "upload_file_form": upload_file_form,
            "graph_loaded": graph_loaded,
            "G": json.dumps(""),
            "G_parent": json.dumps(""),
            "G_sub_graphs": json.dumps(""),
            "clustering": json.dumps("")
        }
        return render(request, 'draw/home.html', context=context)


    if request.method == "POST":
        print "script: views.py,  lineNumber: ", sys._getframe().f_lineno, ",  request.POST: ", request.POST
        upload_file_form = UploadFileForm(request.POST, request.FILES)
        if upload_file_form.is_valid():
            graph_loaded = "true"
            file = upload_file_form.cleaned_data['upload_file']
            file_path = os.path.join(settings.MEDIA_ROOT, 'upload', file.name)
            request.session['file_path'] = file_path
            upload_file = UploadFile()
            if os.path.exists(file_path):
                os.remove(file_path)
                upload_file.file = file
                upload_file.filepath = file_path
                upload_file.filename = file.name
                upload_file.save()
            else:
                upload_file.file = file
                upload_file.filepath = file_path
                upload_file.filename = file.name
                upload_file.save()
            file_path = request.session['file_path']
            try:
                G = gu.import_graph(file_path)
                clustering_method = "ip_seg"
                choose_ip_seg = 2
                largest_cc = max(nx.connected_components(G), key=len) #求最大连通点
                cc_graph = nx.subgraph(G, largest_cc) #最大连通子图
                d = nx.diameter(cc_graph) #最大连通子图的直径
                G_parent, G_sub_graphs, clustering = find_community(G=G,
                                                                   algorithm=clustering_method,
                                                                   ip_seg=choose_ip_seg,
                                                                   with_neighbors=True)
                context = {
                    "upload_file_form": upload_file_form,
                    "graph_loaded": graph_loaded,
                    "G": gu.nx_to_json(G),
                    "G_parent": G_parent,
                    "G_sub_graphs": G_sub_graphs,
                    "clustering": clustering,
                    "diameter": d
                }
            except:
                context = set_empty_context()
                context['graph_loaded'] = "true"
            # else:
            #     context = {"error": "file_type_error"}
            return render(request, 'draw/home.html', context=context)
        if "clustering_method" in request.POST.keys():
            context = setting_form_response(request)
            return HttpResponse(json.dumps(context), content_type="application/json")

        if "search_ip" in request.POST.keys():
            G = gu.import_graph(request.session['file_path'])

            ip = request.POST['search_ip']
            hop = int(request.POST['hop'])
            search_sub_graph, hop_nbunch = search_node(G, ip, hop)
            # search_result = {"search_result": search_node(G, ip, hop)}
            # print "script: view.py, hop_nbunch: ",hop_nbunch
            search_result = {"search_result": search_sub_graph,
                             "hop_nbunch" : json.dumps(hop_nbunch)}
            return HttpResponse(json.dumps(search_result), content_type="application/json")

        if "filter_condition" in request.POST.keys():
            G = gu.import_graph(request.session['file_path'])
            filter_name = request.POST['filter']
            filter_condition = request.POST['filter_condition']
            print "filter: ", filter_name
            print "filter_condition: ", filter_condition
            filter_result = {"filter_result": my_filter(G, filter_name, filter_condition)}
            # filter_result = {"filter_result":""}
            return HttpResponse(json.dumps(filter_result), content_type="application/json")

        if "manage_type" in request.POST.keys():
            context = manage_response(request)
            return HttpResponse(json.dumps(context), content_type="application/json")


def setting_form_response(request):
    clustering_method = request.POST['clustering_method']
    choose_ip_seg = int(request.POST['choose_ip_seg'])
    if request.POST['with_neighbors'] == "yes":
        with_neighbors = True
    else:
        with_neighbors = False

    if 'file_path' in request.session:
        file_path = request.session['file_path']
        G = gu.import_graph(file_path)
        # G = request.session['G']
        G_parent, G_sub_graphs, clustering = find_community(G=G,
                                                          algorithm=clustering_method,
                                                          ip_seg=choose_ip_seg,
                                                          with_neighbors=with_neighbors)
        largest_cc = max(nx.connected_components(G), key=len)  # 求最大连通点
        cc_graph = nx.subgraph(G, largest_cc)  # 最大连通子图
        d = nx.diameter(cc_graph)  # 最大连通子图的直径
        context = {
            "graph_loaded": "true",
            "G": gu.nx_to_json(G),
            "G_parent": G_parent,
            "G_sub_graphs": G_sub_graphs,
            "clustering": clustering,
            "diameter": d
        }
    else:
        context = set_empty_context()
    return context

# 数据增删请求的响应
def manage_response(request):
    print "script: interface.py,  lineNumber:", sys._getframe().f_lineno, ",  func:", sys._getframe().f_code.co_name
    manage_type = request.POST['manage_type']
    print request.POST
    if 'file_path' in request.session:
        # import copy
        file_path = request.session['file_path']
        G = gu.import_graph(file_path)
        if manage_type == 'del_node':
            ip = request.POST['ip']
            result = del_node(G, ip)
        elif manage_type == 'del_edge':
            source_ip = request.POST['source']
            target_ip = request.POST['target']
            result = del_edge(G, source_ip, target_ip)
        elif manage_type == 'add_node':
            ip = request.POST['ip']
            result = my_add_node(G, ip)
        elif manage_type == 'add_edge':
            source_ip = request.POST['source']
            target_ip = request.POST['target']
            temp_G = copy.deepcopy(G)
            result = my_add_edge(temp_G, source_ip, target_ip)
        elif manage_type == 'add_attr':
            ip = request.POST['ip']
            attr_key = request.POST['attr_key']
            attr_value = request.POST['attr_value']
            result = add_attr(G, ip, attr_key, attr_value)
        elif manage_type == 'del_attr':
            ip = request.POST['ip']
            attr_key = request.POST.getlist('attr_key')
            result = del_attr(G, ip, attr_key)

        if "error" in result.keys():
            my_context = {"error": result['error']}
        elif 'G' in result.keys():
            new_G = result['G']
            # temp_fp = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'algo', 'temp.gml')
            # nx.write_gml(result['G'], temp_fp)
            # request.session['file_path'] = temp_fp
            nx.write_gml(result['G'], request.session['file_path'])
            G_parent, G_sub_graphs, clustering = find_community(G=new_G,
                                                                algorithm="ip_seg",
                                                                ip_seg=2,
                                                                with_neighbors=True)
            largest_cc = max(nx.connected_components(new_G), key=len)  # 求最大连通点
            cc_graph = nx.subgraph(new_G, largest_cc)  # 最大连通子图
            d = nx.diameter(cc_graph)  # 最大连通子图的直径
            my_context = {
                "graph_loaded": "true",
                "G": gu.nx_to_json(new_G),
                "G_parent": G_parent,
                "G_sub_graphs": G_sub_graphs,
                "clustering": clustering,
                "diameter": d
            }
    else:
        my_context = set_empty_context()
    return my_context


def set_empty_context():
    empty_context = {
        "graph_loaded": "false",
        "G": json.dumps(""),
        "G_parent": json.dumps(""),
        "G_sub_graphs": json.dumps(""),
        "clustering": json.dumps(""),
        "diameter": 0
    }
    return empty_context


def download(request):
    print "script: views.py,  lineNumber:", sys._getframe().f_lineno, ",  func:", sys._getframe().f_code.co_name
    # f=open('./draw/algo/temp.gml','r')
    f = open(request.session['file_path'], 'r')
    d=f.read()
    f.close()
    return HttpResponse(d, content_type="application/octet-stream")


def fileupload(request):
    print " 'view':", "fileupload",
    print " 'method': ", request.method
    # -------------------------------------
    if request.method == "POST":

mysite/draw/templates/draw/charts.html
<!DOCTYPE html>
<html>
<head>
    <title>charts</title>
    <link href="/static/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
<link href="/static/css/style.css" rel="stylesheet" type="text/css" media=                                                                    "all" />

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <script src="/static/js/d3.min.js"></script>
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/drawCharts.js"></script>

</head>
<body>
    <div class="container">
		<div class="header">
			<div class="header-top">
				<div class="clearfix"> </div>
			</div>
			<div class="header-bottom">
				<div class="top-nav">
					<span class="menu"> </span>
					<ul>
						<li class="active" ><a href="../home" ><span></span>主页</a> </li>
						<li><a href="" data-hover="EVENTS" ><span></span>统计特性</a></li>
					</ul>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
    <div class="container">
        <div class="banner">
            <div class="banner-top"></div>
            <div class="banner-bottom">
                <div class="chart">
                    <div class="svg" id="bar">
                        <label><input type="checkbox"> 按大小排列</label>
                    </div>
                    <div class="svg" id="pie" ></div>

                        <!--<nobr>-->
                            <!--<p>节点的度直方图</p>-->
                            <!--<p>节点的度饼图</p>-->
                        <!--</nobr>-->

                </div>
                <div class="table">
                    <p>节点的度统计表格<p>
                    <table id="table">
                        <!--<caption></caption>-->
                        <tr>
                            <th style="width:200px">节点的度</th>
                            <th style="width:200px">数目</th>
                            <th style="width:900px">id列表</th>
                        </tr>
                    </table>
                    <script type="text/javascript">
                        var degree_detail = {{degree_detail|safe}};
                        console.log(degree_detail);
                    </script>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

mysite/draw/templates/draw/fileupload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>upload</title>
    <link href="/static/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <link href="/static/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
    <style>
        input{
            font-family: myFont;
            line-height: inherit;
        }
        input[type="file"]{
            width: 171px;
            height: 25.6px;
            padding: 3px 0px;
            color: #a9a7a7;
            outline: none;
            left:0px;
        }
        input[type="submit"]{
            position: absolute;
            font-size: 14px;
            margin: 0;
            right: 0px;
        }
    </style>
</head>
<body>
    <form method="POST" enctype="multipart/form-data" id="upload_file_form">
        {% csrf_token %}
        <input class="test_form" id="id_upload_file" name="upload_file" type="file" required/>
        <input type="submit" value="上传" class="btn btn-group btn-dark" id="upload_file_btn">
    </form>
</body>
</html>

mysite/draw/templates/draw/home.html
<!DOCTYPE html>
<html>
<head>
<title>Home</title>
<link href="/static/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
<link href="/static/css/style.css" rel="stylesheet" type="text/css" media="all" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script src="/static/js/jquery.min.js"></script>
<script src="/static/js/d3.min.js"></script>
<script src="/static/js/utils.js"></script> 
<script type="text/javascript" src="/static/js/draw.js"></script>
<script type="text/javascript" src="/static/js/scripts.js"></script>
</head>
<body>
	<div class="container">
		<div class="header">
			<div class="header-top">
				<div class="clearfix"> </div>
			</div>
			<div class="header-bottom">
				<div class="top-nav">
					<span class="menu"> </span>
					<ul>
						<li class="active" ><a href="" ><span></span>主页</a> </li>
						<li><a href="../charts" data-hover="EVENTS" ><span></span>统计特性</a></li>
					</ul>
				</div>
				<div class="search">
					<!--<iframe id="upload_file_iframe" src="/draw/fileupload/" frameborder="no"></iframe>-->
					 <form method="POST" enctype="multipart/form-data" id="upload_file_form">
						{% csrf_token %}
						<input class="test_form" id="id_upload_file" name="upload_file" type="file" required/>

						<input type="submit" value="上传" class="btn btn-group btn-dark" id="upload_file_btn">
					</form>
					<script  type=text/javascript>
							var graph_loaded = {{graph_loaded|safe}};
							var django_data = "";
							var file_uploaded = false;
							if(graph_loaded == true){
								if({{G|safe}} == ""){
									alert("文件错误，请重新上传");
								}else{
									file_uploaded = true;
									console.log("file status: graph loaded")
									django_data = {
										"G" : {{G|safe}} ,
										"G_parent" : {{G_parent|safe}} ,
										"G_sub_graphs" : {{G_sub_graphs|safe}} ,
										"clustering" : {{clustering|safe}}
										};
										console.log(django_data['G']);
								}

							}
							else if(graph_loaded == false){
								file_uploaded = false;
								console.log(" file status: not load");
							}
					</script>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
	<div class="container">
		<div class="header-top">
			<div class="clearfix"> </div>
			<div class="top-nav">
				<span class="menu"> </span>
				<ul>
					<li><input type="button" class="btn btn-group" id="plot_graph_btn" value="网络布局" ></li>
					<li><input type="button" class="btn btn-group" id="plot_hierarchic_btn" value="层次布局" ></li>
					<li class="btn-group dropdown open">
						<input type="button" class="btn dropdown-toggle" data-toggle="dropdown" value="设置">
						<form class="dropdown-menu dropdown-animation settings-form"  method="post">
							<div class ="clustering_method">
							<!--<div class ="clustering_method" style="display:none">-->
								<label for="id_clustering_method_0" class="label_head">选择分层方式:</label>
								<ul id="id_clustering_method">
									<li><label for="id_clustering_method_0"><input class="clustering_method" id="id_clustering_method_0" name="clustering_method" type="radio" value="modularity"/> 模块度</label></li>
									<li><label for="id_clustering_method_1"><input class="clustering_method" id="id_clustering_method_1" name="clustering_method" type="radio" value="ip_seg" checked="checked"/> IP地址</label></li>
								</ul>
							</div>
							<div class="choose_ip_seg">
								<label for="id_choose_ip_seg_0"  class="label_head">选择IP段位:</label>
								<ul id="id_choose_ip_seg">
									<li><label for="id_choose_ip_seg_0"><input class="choose_ip_seg" id="id_choose_ip_seg_0" name="choose_ip_seg" type="radio" value="1"/> 1(<font color="red">***</font>.***.***.***)</label></li><br>
									<li><label for="id_choose_ip_seg_1"><input class="choose_ip_seg" id="id_choose_ip_seg_1" name="choose_ip_seg" type="radio" value="2" checked="checked"/> 2(***.<font color="red">***</font>.***.***)</label></li><br>
									<li><label for="id_choose_ip_seg_2"><input class="choose_ip_seg" id="id_choose_ip_seg_2" name="choose_ip_seg" type="radio" value="3"/> 3(***.***.<font color="red">***</font>.***)</label></li><br>
									<li><label for="id_choose_ip_seg_3"><input class="choose_ip_seg" id="id_choose_ip_seg_3" name="choose_ip_seg" type="radio" value="4"/> 4(***.***.***.<font color="red">***</font>)</label></li>
								</ul>
							</div>
								<div class="with_neighbors">
									<label for="id_choose_ip_seg_0"  class="label_head">是否显示所有邻居节点:</label>
									<ul id="id_with_neighbors">
										<li><label for="id_with_neighbors_1"><input class="with_neighbors" id="id_with_neighbors_1" name="with_neighbors" type="radio" value="yes" checked="checked"/> 是</label></li>
										<li><label for="id_with_neighbors_2"><input class="with_neighbors" id="id_with_neighbors_2" name="with_neighbors" type="radio" value="no"/> 否</label></li>
									</ul>
								</div>
								<input type="button" class="btn btn-group btn-dark submit" id="settings_submit_btn" value="确定">
							</form>
					</li>
					<li class="btn-group dropdown open">
						<input type="button" class="btn dropdown-toggle" data-toggle="dropdown" value="查询">
						<form class="dropdown-menu dropdown-animation"  method="post">
							<label class="control-label">请输入ip:</label><span></span>
							<input type="text" class="form-control" required="required" id="search_input"/>
							<label class="control-label">请选择跳数:</label>
							<input type="number" name="hop" min="0" max={{diameter}} step="1" value="1"/>
							<input type="button" class="btn btn-group btn-dark submit" id="search_submit_btn" value="确定">
						</form>
					</li>
					<li class="btn-group dropdown open">
						<input type="button" class="btn dropdown-toggle" data-toggle="dropdown" value="过滤">
						<form class="dropdown-menu dropdown-animation"  method="post">
							<label class="control-label">过滤器(不区分大小写)：</label><span></span>
							<input type="text" class="form-control" required="required" name="filter" placeholder="例：IP"/>
							<label class="control-label">过滤条件：</label><span></span>
							<input type="text" class="form-control" required="required" name="filter_condition" placeholder="例：192.1.*.*"/>
							<input type="text" class="form-control" required="required" style="display: none"/>
							<input type="button" class="btn btn-group btn-dark submit" id="filter_submit_btn" value="确定">
						</form>
					</li>
					<li class="btn-group dropdown open">
						<input type="button" class="btn dropdown-toggle" data-toggle="dropdown" value="数据操作">
						<ul class="dropdown-menu dropdown-animation">
							<li class="btn manage del_node md-trigger">删除节点</li>
							<li class="btn manage del_edge md-trigger">删除边</li>
							<li class="btn manage add_node md-trigger">增加节点</li>
							<li class="btn manage add_edge md-trigger">增加边</li>
							<li class="btn manage set_center_node md-trigger">设置中心节点</li>
							<li class="btn manage add_attr md-trigger">增加节点属性</li>
							<li class="btn manage del_attr md-trigger">删除节点属性</li>
							</li>
						</ul>
					</li>
					<li class="btn-group dropdown open">
						<input type="button" class="btn dropdown-toggle saveAs" data-toggle="dropdown" value="下载" >
					</li>
				</ul>
			</div>
			<div class="clearfix"> </div>
		</div>
		<i class="line"> </i>
	</div>
	<div class="container">
		<div class="banner">
			<div class="banner-top"></div>
			<div class="banner-bottom">
				<div class="img-responsive line-in" style=" width: 960px;height:640px;border-style:solid;border-width:2px;border-color:#b5b5b5">
					<div id="svg_graph" ></div>
					<div id="svg_hierarchic" ></div>
					<div id="svg_sub_graph"></div>
				</div>
				<div class="dummy-text">
					<div class="doe">
						<h4>图信息</h4>
						<p id="number_of_nodes">节点数目：</p>
						<p id="number_of_edges">边数目：</p>
						<p id="number_of_cluster">聚类数目：</p>
					</div>
					<div class="doe">
						<h4>点信息</h4>
						<p id="node_label">节点IP：</p>
						<p id="node_group">所属类别：</p>
						<p id="node_size">子节点个数：</p>
						<div id="accordion" class="accordion">
							<input type="button" class="btn" value="更多" id="more_information">
							<p class="submenu" id="sql_info"></p>
						</div>
					</div>
					<div class="doe">
						<h4>边信息</h4>
						<p id="source">源节点：</p>
						<p id="target">目的节点：</p>
						<p id="weight">权重：</p>
					</div>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
	<div class="md-popover del_node" id="del_node_div">
		<div class="pop-title">
			<span class="close thick"></span>
			<h4>删除节点</h4>
		</div>
		<div class="pop-body">
			<ul>
				<!--<form method="post">-->
					<li><label class="control-label">标签：</label></li>
					<li><input type="text" class="form-control ip" required="required" placeholder="输入节点IP"/><span></span></li>
					<li></li>
					<li>
						<input class="btn btn-dark submit" type="button" value="删除"/>
						<input class="btn cancel" type="button" value="取消"/>
					</li>
				<!--</form>-->
			</ul>
		</div>
	</div>
	<div class="md-popover del_edge" id="del_edge_div">
		<div class="pop-title">
			<span class="close thick"></span>
			<h4>删除边</h4>
		</div>
		<div class="pop-body">
			<ul>
				<li><strong>源节点：</strong><input type="text" class="form-control ip source" placeholder="输入节点IP"/><span></span></li>
				<li><strong>目的节点：</strong><input type="text" class="form-control  ip target" placeholder="输入节点IP"/><span></span></li>
				<li></li>
				<li>
					<input class="btn btn-dark submit" type="button" value="删除"/>
					<input class="btn cancel" type="button" value="取消"/>
				</li>
			</ul>
		</div>
	</div>
	<div class="md-popover add_node" id="add_node_div">
		<div class="pop-title">
			<span class="close thick"></span>
			<h4>增加节点</h4>
		</div>
		<div class="pop-body">
			<ul>
				<li><label class="control-label">标签</label></li>
				<li><input type="text" class="form-control ip" placeholder="输入节点IP"/><span></span></li>
				<li></li>
				<li>
					<input class="btn btn-dark submit" type="button" value="确定"/>
					<input class="btn cancel" type="button" value="取消"/>
				</li>
			</ul>
		</div>
	</div>
	<div class="md-popover add_edge" id="add_edge_div">
		<div class="pop-title">
			<span class="close thick"></span>
			<h4>增加边</h4>
		</div>
		<div class="pop-body">
			<ul>
				<li><strong>源节点：</strong><input type="text" class="form-control ip source" placeholder="输入节点IP"/><span></span></li>
				<li><strong>目的节点：</strong><input type="text" class="form-control ip target" placeholder="输入节点IP"/><span></span></li>
				<li></li>
				<li>
					<input class="btn btn-dark submit" type="button" value="确定"/>
					<input class="btn cancel" type="button" value="取消"/>
				</li>
			</ul>
		</div>
	</div>
	<div class="md-popover set_center_node" id="set_center_node_div">
		<div class="pop-title">
			<span class="close thick"></span>
			<h4>设置中心节点</h4>
		</div>
		<div class="pop-body">
			<ul>
				<li><label class="control-label">标签</label></li>
				<li><input type="text" class="form-control ip" placeholder="输入节点"/><span></span></li>
				<li id="error_msg"></li>
				<li>
					<input class="btn btn-dark ep_submit" type="button" value="确定"/>
					<input class="btn cancel" type="button" value="取消"/>
				</li>
			</ul>
		</div>
	</div>
	<div class="md-popover add_attr" id="add_attr_div">
		<div class="pop-title">
			<span class="close thick"></span>
			<h4>增加节点属性</h4>
		</div>
		<div class="pop-body">
			<ul>
				<li><strong>节点IP：</strong><input type="text" class="form-control ip" placeholder="输入节点IP"/><span></span></li>
				<li><strong>属性名：</strong><input type="text" class="form-control key" placeholder="输入属性名"/><span></span></li>
				<li><strong>属性值：</strong><input type="text" class="form-control value" placeholder="输入属性值"/><span></span></li>
				<li></li>
				<li>
					<input class="btn btn-dark submit" type="button" value="确定"/>
					<input class="btn cancel" type="button" value="取消"/>
				</li>
			</ul>
		</div>
	</div>
	<div class="md-popover del_attr" id="del_attr_div">
		<div class="pop-title">
			<span class="close thick"></span>
			<h4>删除节点属性</h4>
		</div>
		<div class="pop-body">
			<ul>
				<li><strong>节点IP：</strong><input type="text" class="form-control ip" placeholder="输入节点IP"/><span></span></li>
				<li><strong style="display:none">属性列表：</strong><div id="ckb"></div></li>
				<li></li>
				<!--<div id="ckb"></div>-->
				<li>
					<input class="btn btn-dark submit" type="button" value="删除"/>
					<input class="btn cancel" type="button" value="取消"/>
				</li>
			</ul>
		</div>
	</div>
	<div class="popover-mask">
		<!--这是一个铺满整个页面的div，当弹出弹框时，页面变灰不可操作-->
	</div>
</body>
</html>